name: Build & Publish Wuzzy Search API Image Stage

on:
  push:
    branches: master
env:
  IMAGE_NAME: wuzzy-search-api

jobs:
  push:
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$CONTAINER_REGISTRY_ADDR/${{ github.repository_owner }}/$IMAGE_NAME
          GHCR_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          GHCR_IMAGE_ID=$(echo $GHCR_IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=stage
          echo IMAGE_ID=$IMAGE_ID
          echo GHCR_IMAGE_ID=$GHCR_IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:${GITHUB_SHA}
          docker tag $IMAGE_NAME $IMAGE_ID:${VERSION}
          docker tag $IMAGE_NAME $GHCR_IMAGE_ID:${GITHUB_SHA}
          docker tag $IMAGE_NAME $GHCR_IMAGE_ID:${VERSION}
          docker push $IMAGE_ID:${GITHUB_SHA}
          docker push $IMAGE_ID:${VERSION}
          docker push $GHCR_IMAGE_ID:${GITHUB_SHA}
          docker push $GHCR_IMAGE_ID:${VERSION}

      - name: Deploy new version
        run: |
          sed -i "s/\[\[ .commit_sha \]\]/${GITHUB_SHA}/g" operations/wuzzy-search-api-stage.hcl
          nomad job run operations/wuzzy-search-api-stage.hcl

